version: '3.8'

services:

  web:
    build: .
    image: 458694677747.dkr.ecr.us-east-1.amazonaws.com/flask-celery-poc-web:${FLASK_CELERY_POC_IMAGE_TAG}
    container_name: web
    ports:
      - 5004:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    image: 458694677747.dkr.ecr.us-east-1.amazonaws.com/flask-celery-poc-worker:${FLASK_CELERY_POC_IMAGE_TAG}
    command: celery --app project.server.tasks.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: .
    image: 458694677747.dkr.ecr.us-east-1.amazonaws.com/flask-celery-poc-dashboard:${FLASK_CELERY_POC_IMAGE_TAG}
    command: celery --app project.server.tasks.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker